name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name:  Build Docker image
        uses:  docker build -t mysanth-portfolio . 

      - name: Run container (for test/demo purposes)
        uses: docker run -d -p 82:82 mysanth-portfolio
